In [1]:
import numpy as np


# 기본적인 attention

In [2]:
T, H = 5, 4
hs = np.random.randn(T, H)
a = np.array([0.8, 0.1, 0.03, 0.03, 0.02])

In [3]:
ar = a.reshape(5, 1).repeat(4, axis=1)

In [4]:
ar

array([[0.8 , 0.8 , 0.8 , 0.8 ],
       [0.1 , 0.1 , 0.1 , 0.1 ],
       [0.03, 0.03, 0.03, 0.03],
       [0.03, 0.03, 0.03, 0.03],
       [0.02, 0.02, 0.02, 0.02]])

In [5]:
ar.shape

(5, 4)

In [6]:
hs

array([[ 0.5214741 ,  0.46910803, -0.07580578,  1.96593354],
       [-0.23213271,  0.9372682 ,  1.11027714, -1.33754991],
       [ 0.36601293,  1.96550385, -2.94200074, -0.28344818],
       [ 0.15509472, -0.2019942 ,  0.20658534, -1.70600089],
       [-0.81572537, -0.47951408, -0.87765891,  1.69013291]])

In [7]:
t = hs*ar

In [8]:
t

array([[ 0.41717928,  0.37528642, -0.06064462,  1.57274683],
       [-0.02321327,  0.09372682,  0.11102771, -0.13375499],
       [ 0.01098039,  0.05896512, -0.08826002, -0.00850345],
       [ 0.00465284, -0.00605983,  0.00619756, -0.05118003],
       [-0.01631451, -0.00959028, -0.01755318,  0.03380266]])

In [9]:
t.shape

(5, 4)

In [10]:
c = np.sum(t, axis=0)
c

array([ 0.39328474,  0.51232825, -0.04923255,  1.41311103])

In [12]:
c.shape

(4,)

# 미니배치 처리용 attention

In [13]:
N, T, H = 10, 5, 4
hs = np.random.randn(N, T, H)
a = np.random.randn(N, T)
ar = a.reshape(N, T, 1).repeat(H, axis=2)

In [14]:
ar.shape

(10, 5, 4)

In [15]:
a.shape

(10, 5)

In [17]:
t = hs * ar

In [18]:
t.shape

(10, 5, 4)

In [19]:
c = np.sum(t, axis=1)
c.shape

(10, 4)

# weighted sum 실습

In [10]:
import import_ipynb
import sys
sys.path.append('..')
from common.layers import Softmax
import numpy as np

In [5]:
N, T, H = 10, 5, 4
hs = np.random.randn(N, T, H)
h = np.random.randn(N, H)
hr = h.reshape(N, 1, H).repeat(T, axis=1)


In [7]:
t = hs*hr
t.shape

(10, 5, 4)

In [8]:
s = np.sum(t, axis=2)
s.shape

(10, 5)

In [11]:
softmax = Softmax()
a = softmax.forward(s)
a.shape

(10, 5)