# 가중치 레이어에서 정해진 인덱스 추출

In [1]:
import numpy as np

In [3]:
W = np.arange(21).reshape(7, 3)
W

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

In [4]:
W[2]

array([6, 7, 8])

In [5]:
W[5]

array([15, 16, 17])

In [6]:
idx = np.array([1, 0, 3, 0])
W[idx]

array([[ 3,  4,  5],
       [ 0,  1,  2],
       [ 9, 10, 11],
       [ 0,  1,  2]])

# np.random.choice()

In [8]:
import numpy as np

In [9]:
np.random.choice(10)

6

In [12]:
words = [ 'you','say','goodbye','I', "hello", '.']
np.random.choice(words)

'say'

In [13]:
# 5개 무작위 샘플링(복원추출)
np.random.choice(words, size = 5)

array(['goodbye', '.', '.', 'say', 'I'], dtype='<U7')

In [16]:
# 비복원 추출
np.random.choice(words, size=5, replace=False)

array(['say', 'goodbye', 'I', '.', 'you'], dtype='<U7')

In [17]:
# 확률 분포에 따라 샘플링
p = [0.5, 0.1, 0.05, 0.2, 0.05, 0.1]
np.random.choice(words, p=p)

'.'

# 0.75 제곱의 적용

In [18]:
p = [0.7, 0.29, 0.01]
new_p = np.power(p, 0.75)
new_p /= np.sum(new_p)
new_p

array([0.64196878, 0.33150408, 0.02652714])