In [2]:
import import_ipynb
import sys
sys.path.append('..')
import numpy as np
import matplotlib.pyplot as plt
from dataset import sequence
from common.optimizer import Adam
from common.trainer import Trainer
from common.util import eval_seq2seq
from seq2seq import Seq2seq

importing Jupyter notebook from ../dataset/sequence.ipynb
importing Jupyter notebook from ../common/optimizer.ipynb
importing Jupyter notebook from ../common/trainer.ipynb
importing Jupyter notebook from ../common/util.ipynb
importing Jupyter notebook from seq2seq.ipynb
importing Jupyter notebook from ../common/time_layers.ipynb
importing Jupyter notebook from ../common/layers.ipynb
importing Jupyter notebook from ../common/functions.ipynb
importing Jupyter notebook from ../common/base_model.ipynb


In [4]:
#  데이터셋 읽기
(x_train, t_train), (x_test, t_test) = sequence.load_data('addition.txt')
x_train, x_test = x_train[:, ::-1], x_test[:, ::-1]
char_to_id, id_to_char = sequence.get_vocab()

In [5]:
# 하이퍼파라미터 설정
vocab_size = len(char_to_id)
wordvec_size = 16
hidden_size = 128
batch_size = 128
max_epoch = 25
max_grad = 5.0

In [6]:
# 객체들 설정
model = Seq2seq(vocab_size, wordvec_size, hidden_size)
optimizer = Adam()
trainer = Trainer(model, optimizer)

In [5]:
acc_list = []
for epoch in range(max_epoch):
    trainer.fit(x_train, t_train, max_epoch = 1, batch_size = batch_size, max_grad = max_grad)
    correct_num = 0
    for i in range(len(x_test)): 
        question, correct = x_test[[i]], t_test[[i]]
        verbose = i<10
        correct_num += eval_seq2seq(model, question, correct, id_to_char, verbose)
    acc = float(correct_num) / len(x_test)
    acc_list.append(acc)
    print('검증 정확도 : {}'.format(acc * 100, ".3f"))

| 에폭 1 |  반복 1 / 351 | 시간 0[s] | 손실 2.56
| 에폭 1 |  반복 21 / 351 | 시간 1[s] | 손실 2.53
| 에폭 1 |  반복 41 / 351 | 시간 2[s] | 손실 2.17
| 에폭 1 |  반복 61 / 351 | 시간 3[s] | 손실 1.96
| 에폭 1 |  반복 81 / 351 | 시간 5[s] | 손실 1.92
| 에폭 1 |  반복 101 / 351 | 시간 6[s] | 손실 1.87
| 에폭 1 |  반복 121 / 351 | 시간 7[s] | 손실 1.85
| 에폭 1 |  반복 141 / 351 | 시간 8[s] | 손실 1.83
| 에폭 1 |  반복 161 / 351 | 시간 9[s] | 손실 1.79
| 에폭 1 |  반복 181 / 351 | 시간 10[s] | 손실 1.77
| 에폭 1 |  반복 201 / 351 | 시간 12[s] | 손실 1.77
| 에폭 1 |  반복 221 / 351 | 시간 13[s] | 손실 1.76
| 에폭 1 |  반복 241 / 351 | 시간 15[s] | 손실 1.76
| 에폭 1 |  반복 261 / 351 | 시간 16[s] | 손실 1.76
| 에폭 1 |  반복 281 / 351 | 시간 17[s] | 손실 1.75
| 에폭 1 |  반복 301 / 351 | 시간 19[s] | 손실 1.74
| 에폭 1 |  반복 321 / 351 | 시간 20[s] | 손실 1.75
| 에폭 1 |  반복 341 / 351 | 시간 21[s] | 손실 1.74
Q 77+85  
T 162 
☒ 100 
---
Q 975+164
T 1139
☒ 1000
---
Q 582+84 
T 666 
☒ 1000
---
Q 8+155  
T 163 
☒ 100 
---
Q 367+55 
T 422 
☒ 1000
---
Q 600+257
T 857 
☒ 1000
---
Q 761+292
T 1053
☒ 1000
---
Q 830+597
T 1427
☒ 1000
---

| 에폭 8 |  반복 21 / 351 | 시간 1[s] | 손실 1.03
| 에폭 8 |  반복 41 / 351 | 시간 2[s] | 손실 1.03
| 에폭 8 |  반복 61 / 351 | 시간 5[s] | 손실 1.04
| 에폭 8 |  반복 81 / 351 | 시간 9[s] | 손실 1.03
| 에폭 8 |  반복 101 / 351 | 시간 10[s] | 손실 1.05
| 에폭 8 |  반복 121 / 351 | 시간 12[s] | 손실 1.05
| 에폭 8 |  반복 141 / 351 | 시간 14[s] | 손실 1.04
| 에폭 8 |  반복 161 / 351 | 시간 15[s] | 손실 1.05
| 에폭 8 |  반복 181 / 351 | 시간 16[s] | 손실 1.03
| 에폭 8 |  반복 201 / 351 | 시간 17[s] | 손실 1.03
| 에폭 8 |  반복 221 / 351 | 시간 19[s] | 손실 1.02
| 에폭 8 |  반복 241 / 351 | 시간 20[s] | 손실 1.02
| 에폭 8 |  반복 261 / 351 | 시간 21[s] | 손실 1.01
| 에폭 8 |  반복 281 / 351 | 시간 23[s] | 손실 1.03
| 에폭 8 |  반복 301 / 351 | 시간 24[s] | 손실 1.01
| 에폭 8 |  반복 321 / 351 | 시간 26[s] | 손실 1.05
| 에폭 8 |  반복 341 / 351 | 시간 27[s] | 손실 1.00
Q 77+85  
T 162 
☒ 158 
---
Q 975+164
T 1139
☒ 1109
---
Q 582+84 
T 666 
☒ 656 
---
Q 8+155  
T 163 
☒ 156 
---
Q 367+55 
T 422 
☒ 431 
---
Q 600+257
T 857 
☒ 838 
---
Q 761+292
T 1053
☒ 1009
---
Q 830+597
T 1427
☒ 1411
---
Q 26+838 
T 864 
☒ 861 
---
Q 143+93

| 에폭 15 |  반복 21 / 351 | 시간 1[s] | 손실 0.89
| 에폭 15 |  반복 41 / 351 | 시간 2[s] | 손실 0.89
| 에폭 15 |  반복 61 / 351 | 시간 4[s] | 손실 0.89
| 에폭 15 |  반복 81 / 351 | 시간 5[s] | 손실 0.89
| 에폭 15 |  반복 101 / 351 | 시간 7[s] | 손실 0.90
| 에폭 15 |  반복 121 / 351 | 시간 8[s] | 손실 0.89
| 에폭 15 |  반복 141 / 351 | 시간 9[s] | 손실 0.89
| 에폭 15 |  반복 161 / 351 | 시간 11[s] | 손실 0.91
| 에폭 15 |  반복 181 / 351 | 시간 12[s] | 손실 0.90
| 에폭 15 |  반복 201 / 351 | 시간 13[s] | 손실 0.90
| 에폭 15 |  반복 221 / 351 | 시간 15[s] | 손실 0.90
| 에폭 15 |  반복 241 / 351 | 시간 16[s] | 손실 0.88
| 에폭 15 |  반복 261 / 351 | 시간 18[s] | 손실 0.87
| 에폭 15 |  반복 281 / 351 | 시간 19[s] | 손실 0.88
| 에폭 15 |  반복 301 / 351 | 시간 20[s] | 손실 0.87
| 에폭 15 |  반복 321 / 351 | 시간 21[s] | 손실 0.86
| 에폭 15 |  반복 341 / 351 | 시간 23[s] | 손실 0.86
Q 77+85  
T 162 
☒ 161 
---
Q 975+164
T 1139
☒ 1107
---
Q 582+84 
T 666 
☑ 666 
---
Q 8+155  
T 163 
☒ 158 
---
Q 367+55 
T 422 
☒ 412 
---
Q 600+257
T 857 
☒ 849 
---
Q 761+292
T 1053
☒ 1039
---
Q 830+597
T 1427
☒ 1414
---
Q 26+838 
T 864 
☒ 868

검증 정확도 : 6.7
| 에폭 22 |  반복 1 / 351 | 시간 0[s] | 손실 0.84
| 에폭 22 |  반복 21 / 351 | 시간 2[s] | 손실 0.80
| 에폭 22 |  반복 41 / 351 | 시간 5[s] | 손실 0.81
| 에폭 22 |  반복 61 / 351 | 시간 7[s] | 손실 0.81
| 에폭 22 |  반복 81 / 351 | 시간 9[s] | 손실 0.81
| 에폭 22 |  반복 101 / 351 | 시간 11[s] | 손실 0.80
| 에폭 22 |  반복 121 / 351 | 시간 14[s] | 손실 0.79
| 에폭 22 |  반복 141 / 351 | 시간 15[s] | 손실 0.81
| 에폭 22 |  반복 161 / 351 | 시간 16[s] | 손실 0.80
| 에폭 22 |  반복 181 / 351 | 시간 18[s] | 손실 0.84
| 에폭 22 |  반복 201 / 351 | 시간 19[s] | 손실 0.79
| 에폭 22 |  반복 221 / 351 | 시간 20[s] | 손실 0.81
| 에폭 22 |  반복 241 / 351 | 시간 21[s] | 손실 0.80
| 에폭 22 |  반복 261 / 351 | 시간 23[s] | 손실 0.78
| 에폭 22 |  반복 281 / 351 | 시간 25[s] | 손실 0.79
| 에폭 22 |  반복 301 / 351 | 시간 26[s] | 손실 0.83
| 에폭 22 |  반복 321 / 351 | 시간 27[s] | 손실 0.82
| 에폭 22 |  반복 341 / 351 | 시간 29[s] | 손실 0.81
Q 77+85  
T 162 
☒ 160 
---
Q 975+164
T 1139
☒ 1129
---
Q 582+84 
T 666 
☒ 657 
---
Q 8+155  
T 163 
☒ 157 
---
Q 367+55 
T 422 
☒ 419 
---
Q 600+257
T 857 
☒ 855 
---
Q 761+292
T 1053
☒ 1

In [6]:
print(t_test)
print(t_test.shape)

[[ 6  0  1  8  5]
 [ 6  0  0 10  7]
 [ 6  1  1  1  5]
 ...
 [ 6  7  9 12  5]
 [ 6  0  9  8 10]
 [ 6  3  9 12  5]]
(5000, 5)
